# Generated by Django 4.1.5 on 2024-05-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=20)),
                ('categorydesc', models.TextField(max_length=100)),
                ('categoryimg', models.ImageField(default='null.jpg', upload_to='sample')),
            ],
        ),
        migrations.CreateModel(
            name='Prdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=20)),
                ('productcat', models.CharField(max_length=20)),
                ('productimg', models.ImageField(default='null.jpg', upload_to='sample')),
            ],
        ),
    ]
