# Generated by Django 4.1.5 on 2024-05-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prdb',
            name='productprc',
            field=models.IntegerField(default=0),
        ),
    ]
