# Generated by Django 4.1.5 on 2024-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactmsg', models.TextField(max_length=100)),
                ('contactname', models.CharField(max_length=20)),
                ('contactmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
