# Generated by Django 4.2.7 on 2024-05-22 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_prdb_productprc'),
        ('userapp', '0002_condb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cqty', models.IntegerField()),
                ('ctot', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('prdid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.prdb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.regdb')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=60)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('postalcode', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('cartid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.cartdb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.regdb')),
            ],
        ),
    ]
